# Generated by Django 2.0.8 on 2018-08-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trademark_title', models.CharField(max_length=80)),
                ('trademark_image', models.ImageField(upload_to='')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('payment_date', models.DateTimeField()),
                ('filed_date', models.DateTimeField()),
                ('application_number', models.CharField(max_length=80)),
                ('publication_number', models.CharField(max_length=80)),
                ('publication_date', models.CharField(max_length=80)),
                ('registration_number', models.CharField(max_length=80)),
                ('registration_date', models.CharField(max_length=80)),
                ('products', models.TextField()),
                ('product_comment', models.TextField()),
                ('progress_status', models.CharField(choices=[('결제 대기 중', '결제 대기 중'), ('출원 준비 중', '출원 준비 중'), ('심사 중', '심사 중'), ('출원공고', '출원공고'), ('거절 대응 중', '거절 대응 중'), ('등록', '등록'), ('갱신 대상', '갱신 대상')], max_length=80)),
            ],
        ),
    ]
