# Generated by Django 2.0.8 on 2018-08-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
