# Generated by Django 2.0.8 on 2018-08-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180827_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='applicant_number',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cumulative_pay_amount',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cumulative_usage_count',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='push_token',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signature_image',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='social_number',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
